title: "METS IEDC"
description: "Official website of METS IEDC"
url: "https://mets-iedc.github.io"

plugins:
  - jekyll-sitemap

# (Optional) Exclude pages you don’t want in sitemap
exclude:
  - Archaena.html
  - sharktank_demo.html
  - googled1154617d00ca8d2.html
